# Local components
external_components:
  - source: components

api:
  actions:
    # HA API to configure the exhaust and supply fan levels in percentage
    - action: configure_fan_levels
      variables:
        exhaust_level_absent: int
        exhaust_level_low: int
        exhaust_level_mid: int
        exhaust_level_high: int
        supply_level_absent: int
        supply_level_low: int
        supply_level_mid: int
        supply_level_high: int
      then:
        - lambda: "id(comfoair_180).configure_fan_levels(exhaust_level_absent, exhaust_level_low, exhaust_level_mid, exhaust_level_high, supply_level_absent, supply_level_low, supply_level_mid, supply_level_high);"

uart:
  # Communication channel with comfoair
  - id: uart_bus
    baud_rate: 9600
    tx_pin: 10
    rx_pin: 9
  # Communication channel with remote controller
  - id: uart_proxy
    baud_rate: 9600
    tx_pin: 11
    rx_pin: 12

button:
  - platform: template
    id: reset_filter_button
    name: "Reset Filter"
    on_press: 
      then:
        lambda: "id(comfoair_180).filter_reset();"

comfoair:
  id: comfoair_180
  name: "ComfoAir 180"
  uart_id: uart_bus
  proxy_uart: uart_proxy
  # === Fan status ===
  intake_fan_speed:
    name: "Supply air level"
  exhaust_fan_speed:
    name: "Return air level"
  intake_fan_speed_rpm:
    name: "Intake fan RPM"
  exhaust_fan_speed_rpm:
    name: "Exhaust fan RPM"
  # === Valve status ===
  bypass_valve:
    name: "Bypass valve"
  bypass_valve_open:
    name: "Bypass open"
  summer_mode:
    name: "Summer mode"
  # === Ventilation level ===
  ventilation_level:
    name: "Ventilation level"
  supply_fan_active:
    name: "Supply fan active"
  # === Faults ===
  filter_status:
    name: "Filter status"
    id: filter_status
    on_value:
      then:
        - script.execute: show_led_status
  # === Temperatures ===
  outside_air_temperature:
    name: "Outside temperature"
  supply_air_temperature:
    name: "Supply temperature"
  return_air_temperature:
    name: "Return temperature"
  exhaust_air_temperature:
    name: "Exhaust temperature"
  # === Operation hours ===
  level0_hours:
    name: "Level 0 hours"
  level1_hours:
    name: "Level 1 hours"
  level2_hours:
    name: "Level 2 hours"
  level3_hours:
    name: "Level 3 hours"
  frost_protection_hours:
    name: "Frost protection hours"
  bypass_open_hours:
    name: "Bypass open hours"
  preheating_hours:
    name: "Preheating hours"
  filter_hours:
    name: "Filter hours"
